stages:
  - test
# - stage

code_quality:
  stage: test
  allow_failure: true
  image: node:15-alpine
  script:
    - cd frontend/ && npx prettier --check .

backend_tests:
  stage: test
  image: golang:1.16
  script:
    - cd server/ && go test -v ./...

#create_docker_image:
#  stage: stage
#  only:
#    - master
#  image: docker:dind
#  script:
#    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#    - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH:dev .
#    - docker push $CI_REGISTRY/$CI_PROJECT_PATH:dev
