version: '3'
services:

  mongo:
    image: mongo:latest
    container_name: paqman-db
    restart: always
    volumes:
      - paqman-db-vol:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor

  paqman:
    image: registry.git.leon.wtf/paqman/paqman:dev
    container_name: paqman
    restart: always
    ports:
      - 3002:3002
    #volumes:
    #  - ./config.json:/config.json:ro

volumes:
  paqman-db-vol: